-- Newton Labs Test Data
-- Frequently Booked Tests (Lowest Prices First)

-- Insert Tests (Sorted by lowest price first for "Frequently Booked Tests")
-- Using ON CONFLICT to avoid duplicate key errors on restart
INSERT INTO tests (name, price, mrp, sample_type, tat, department, category, fasting_required, status) VALUES
('Glucose - Postprandial', 40, 40, 'Plasma Naf', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Glucose - Random', 40, 40, 'Naf Plasma', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Glucose - Fasting', 50, 50, 'Naf Plasma', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', true, 'active'),
('Cholesterol - Total', 50, 50, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Creatinine - 24 Hr Urine', 50, 50, 'Urine', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Uric Acid - Serum', 50, 50, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Calcium - 24 Hr Urine', 80, 80, 'Urine', '6 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Fasting Urine Glucose', 80, 80, 'Urine', '', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Phosphorus - 24 Hr Urine', 100, 100, 'Urine', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Thyroxine - Total (TT4)', 100, 100, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Triglycerides (TGL)', 100, 100, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Urea', 100, 100, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Bilirubin Direct', 100, 100, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Albumin', 100, 100, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Alkaline Phosphatase (ALP)', 100, 100, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Gamma Glutamyl Transferase (GGT)', 100, 100, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Estimated Average Glucose (eAG)', 100, 100, 'WB EDTA', '', 'HAEMATOLOGY', 'HAEMATOLOGY', false, 'active'),
('Urea/Creatinine Ratio', 100, 100, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Glucose-1hr', 100, 100, 'Naf Plasma', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Urea 24 hrs Urine', 100, 100, 'Urine', '8 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Creatinine - Serum', 100, 100, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Alanine Transaminase (ALT/SGPT)', 100, 100, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('AST / ALT', 100, 100, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Protein Total with Albumin', 100, 100, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Bilirubin Total', 100, 100, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Random Urine Glucose', 100, 100, 'Urine', '', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Protein Total', 100, 100, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Globulin', 100, 100, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Thyroid Stimulating Hormone (TSH)', 100, 100, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Calcium - Serum', 100, 100, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Aspartate Aminotransferase (AST/SGOT)', 100, 100, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Protein - Fluids', 100, 100, 'Naf Plasma', '8 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Post Prandial Urine Glucose', 100, 100, 'Urine', '', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Protein - Random (Spot)', 120, 120, 'Urine', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('24hrs Urinary Protein', 120, 120, 'Urine', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Protein (CSF)', 120, 120, 'CSF', '', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Creatine Kinase (CPK)', 130, 130, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Glucose Challenge Test', 150, 150, 'Naf Plasma', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Phosphorus - Serum', 150, 150, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Triiodothyronine Total (TT3)', 150, 150, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Absolute Basophil Count', 150, 150, 'WB EDTA', '8 hr', 'HAEMATOLOGY', 'HAEMATOLOGY', false, 'active'),
('Absolute Eosinophil Count (AEC)', 150, 150, 'WB EDTA', '6 hr', 'HAEMATOLOGY', 'HAEMATOLOGY', false, 'active'),
('Iron Binding Capacity - Total (TIBC)', 150, 150, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Protein Creatinine Ratio, Urine', 160, 160, 'Urine', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Creatinine Clearence Test (CCT)', 160, 160, 'Urine', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Bilirubin (Total + Direct)', 160, 160, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active');

-- More Tests
INSERT INTO tests (name, price, mrp, sample_type, tat, department, category, fasting_required, status) VALUES
('Iron', 200, 200, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Lactate Dehydrogenase (LDH) - Serum', 200, 200, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Glomerular Filtration Rate (eGFR)', 200, 200, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Amylase Serum', 225, 225, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Amylase Urine', 225, 225, 'Urine', '6 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Oral Glucose Tolerance Test (O-GTT)', 240, 240, 'Naf Plasma', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Follicle Stimulating Hormone (FSH)', 250, 250, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Cholesterol - HDL', 250, 250, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Lactate CSF', 250, 250, 'CSF', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Luteinising Hormone (LH)', 250, 250, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Thyroid Profile-I', 250, 250, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Lactate NaF Plasma', 250, 250, 'Naf Plasma', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Fluid Examination Routine Pleural Fluid', 250, 250, 'Pleural Fluid', '8 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Cholesterol - LDL', 250, 250, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Cholesterol VLDL', 250, 250, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Prolactin (PRL)', 250, 250, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Total cholesterol/HDL ratio', 300, 300, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('TGL /HDL Ratio', 300, 300, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Triiodothyronine Free (FT3)', 300, 300, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Thyroxine - Free (FT4)', 300, 300, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('eGFR', 300, 300, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Complete Blood Picture (CBP)', 300, 300, 'WB EDTA', '6 hr', 'HAEMATOLOGY', 'HAEMATOLOGY', false, 'active'),
('Copper - Serum', 350, 350, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Copper - 24 Hr Urine', 350, 350, 'Urine', '6 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Alpha Feto Protein (AFP) - Ascitic Fluid', 350, 350, 'Ascitic Fluid', '6 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Pregnancy Test', 400, 400, 'Urine', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Potassium - 24 Hr Urine', 400, 400, 'Urine', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Osmolality', 400, 400, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Kidney Function Test', 400, 400, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Sodium - Serum', 400, 400, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Chloride - CSF', 400, 400, 'CSF', '6 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Chloride - 24 Hr Urine', 400, 400, 'Urine', '6 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Potassium - Serum', 400, 400, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Electrolyte Profile', 400, 400, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Sodium - 24 Hr Urine', 400, 400, 'Urine', '8 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Chloride - Serum', 400, 400, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Zinc Serum', 400, 400, 'Serum', '10 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Ionized Calcium', 400, 400, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Bicarbonate', 400, 400, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Aerobic C&S Miscellaneous DD', 400, 400, 'Miscellaneous', '2 Days', 'MICROBIOLOGY', 'MICROBIOLOGY', false, 'active'),
('Progesterone', 450, 450, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Lipid Profile [9]', 450, 450, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Coombs Test Indirect', 450, 450, 'Serum', '2 Days', 'IMMUNO-HEMATOLOGY', 'IMMUNO-HEMATOLOGY', false, 'active'),
('Liver Function Test [13]', 480, 480, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active');

-- More Tests (continued)
INSERT INTO tests (name, price, mrp, sample_type, tat, department, category, fasting_required, status) VALUES
('IRON PROFILE', 500, 500, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Prostarate Specific Antigen, PSA Total', 500, 500, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Thyroid Profile - III', 500, 500, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Thyroid Profile-II', 500, 500, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Estradiol (E2)', 500, 500, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Electrolytes Profile Urine', 500, 500, 'Urine', '', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Immunofixation Electrophoresis - Urine', 500, 500, 'Urine', '3 Days', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Urine Albumin (Microalbumin) / Creatinine Ratio', 525, 525, 'Urine', '6 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('C-Reactive Protein (CRP)', 550, 550, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Thyroid Profile-IV', 550, 550, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('IgG (CSF)', 550, 550, 'CSF', '', 'IMMUNOLOGY / SEROLOGY', 'IMMUNOLOGY / SEROLOGY', false, 'active'),
('High Sensitive CRP (hsCRP)', 550, 550, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Beta Human Chorionic Gonodotropin Hormone (Beta HCG) - Serum', 550, 550, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Ferritin', 550, 550, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Folate Serum (Folic Acid)', 550, 550, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Carcino Embryonic Antigen (CEA)', 560, 560, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Vitamin - B12', 600, 600, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Microalbumin', 600, 600, 'Urine', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Glycosylated Hemoglobin (GHb/HBA1c)', 600, 600, 'WB EDTA', '6 hr', 'HAEMATOLOGY', 'HAEMATOLOGY', false, 'active'),
('Ketone Bodies, Serum', 600, 600, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Testosterone - TOTAL', 600, 600, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Ammonia', 600, 600, 'EDTA Plasma', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Alpha Feto Protein (AFP) Serum', 600, 600, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Rheumatoid Factor (RA Test)', 600, 600, 'Serum', '1 Day', 'IMMUNOLOGY / SEROLOGY', 'IMMUNOLOGY / SEROLOGY', false, 'active'),
('Lipid Profile', 650, 650, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Lipoprotein a (Lp-a)', 650, 650, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Iron Deficiency Profile', 650, 650, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Troponin - I', 650, 650, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Apolipoprotein B (APO-B)', 650, 650, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Apolipoprotein A1 (APO-A1)', 650, 650, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Liver Function Profile', 700, 700, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Complement 3 (C3)', 700, 700, 'Serum', '1 Day', 'IMMUNOLOGY / SEROLOGY', 'IMMUNOLOGY / SEROLOGY', false, 'active'),
('Complement 4 (C4)', 700, 700, 'Serum', '6 hr', 'IMMUNOLOGY / SEROLOGY', 'IMMUNOLOGY / SEROLOGY', false, 'active'),
('Total IgE', 700, 700, 'Serum', '8 hr', 'IMMUNOLOGY / SEROLOGY', 'IMMUNOLOGY / SEROLOGY', false, 'active'),
('Fertility Profile - I', 750, 750, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Osmotic Fragility Test', 750, 750, 'WB Na Heparin', '1 Day', 'HAEMATOLOGY', 'HAEMATOLOGY', false, 'active'),
('Lipase Serum', 800, 800, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Osmolality Urine', 800, 800, 'Urine', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Anti Microsomal/Thyroperoxidase Antibody (Anti TPO)', 800, 800, 'Serum', '6 hr', 'IMMUNOLOGY / SEROLOGY', 'IMMUNOLOGY / SEROLOGY', false, 'active'),
('Testosterone - Free', 800, 800, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Transferrin', 800, 800, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Transferrin %', 800, 800, 'Serum', '8 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Acid Phosphatase - Total', 800, 800, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Bile Acids Total', 800, 800, 'Serum', '4 Days', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('CA 125 Ovarian Cancer marker', 850, 850, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Growth Hormone (HGH)', 850, 850, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active');

-- More Tests (continued)
INSERT INTO tests (name, price, mrp, sample_type, tat, department, category, fasting_required, status) VALUES
('Sex Hormone Binding Globulin (SHBG)', 900, 900, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Creatine Kinase (CK-MB)', 900, 900, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Vitamin D', 900, 900, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('25-Hydroxy Vitamin D Total (D2 & D3)', 900, 900, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Cortisol (Saliva)', 900, 900, 'Saliva', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Beta Human Chorionic Gonodotropin Hormone (Free Beta HCG)', 900, 900, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Estriol, Unconjugated (E3)', 900, 900, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Cortisol Urine', 900, 900, 'Urine', '6 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Cortisol Serum (3 to 5 PM)', 900, 900, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Cortisol Serum (7 to 9 AM)', 900, 900, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Homocysteine', 900, 900, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Angiotensin Converting Enzyme (ACE) CSF', 900, 900, 'CSF', '8 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Phenytoin (Eptoin)', 900, 900, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Second Trimester Risk', 1000, 1000, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Ceruloplasmin', 1000, 1000, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Insulin - Post prandial', 1000, 1000, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Insulin Fasting', 1000, 1000, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('HOMA-IR (Insulin Resistance)', 1000, 1000, 'Serum / Naf Plasma', '2 Days', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Vitamin Profile', 1000, 1000, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Anti Thyroglobulin Antibody (ATG)', 1200, 1200, 'Serum', '6 hr', 'IMMUNOLOGY / SEROLOGY', 'IMMUNOLOGY / SEROLOGY', false, 'active'),
('Protein Electrophoresis - Serum', 1200, 1200, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Bence Jones Protein (BJ Protein)', 1200, 1200, 'Urine', '8 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('PAPP-A', 1200, 1200, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Zinc (ICP-AAS)', 1200, 1200, 'Serum', '4 Days', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Troponin - T (CLIA)', 1250, 1250, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Benzodiazepines', 1250, 1250, 'Urine', '6 hr', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Intact Parathyroid Hormone (iPTH)', 1500, 1500, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('C-Peptide', 1500, 1500, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Arthiritis Basic Screen', 1500, 1500, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Triple Marker With Graph', 1500, 1500, 'Serum', '2 Days', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Thyroxin Binding Globulin', 1500, 1500, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Stone Analysis', 1500, 1500, 'Stone', '3 Days', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Dual Marker With Graph', 1600, 1600, 'Serum', '2 Days', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Citric Acid Serum', 1600, 1600, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('HOMA-IR-2 Insulin Resistance', 1600, 1600, 'Serum / Naf Plasma', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Beta -2 Microglobulin Urine', 1800, 1800, 'Urine', '2 Days', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Beta 2 Microglobulin Serum', 1800, 1800, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Quad Marker With Graph', 2000, 2000, 'Serum', '2 Days', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Oxalates - Plasma', 2000, 2000, 'EDTA Plasma', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('SOY', 2000, 2000, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Erythropoietin (EPO)', 2250, 2250, 'Serum', '6 hr', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Syphilis Antibodies (Total)', 2500, 2500, 'Serum', '1 Day', 'IMMUNOLOGY / SEROLOGY', 'IMMUNOLOGY / SEROLOGY', false, 'active'),
('Procalcitonin', 2500, 2500, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('1,25 Di Hydroxy Vitamin D', 2500, 2500, 'Serum', '1 Day', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Drugs of Abuse (5 Drugs)', 2500, 2500, 'Urine', '', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('Kidney Function Test Advanced', 2836, 2836, 'Serum', '', 'CLINICAL BIOCHEMISTRY', 'CLINICAL BIOCHEMISTRY', false, 'active'),
('Calprotectin Stool', 3000, 3000, 'Stool', '1 Day', 'CLINICAL PATHOLOGY', 'CLINICAL PATHOLOGY', false, 'active'),
('CD14', 3500, 3500, 'WB EDTA', '3 Days', 'HAEMATOLOGY', 'HAEMATOLOGY', false, 'active'),
('Factor XIII Activity', 6500, 6500, 'Citrated Plasma', '2 Days', 'HAEMATOLOGY', 'HAEMATOLOGY', false, 'active'),
('CA 19-9 IHC MARKER', 6800, 6800, 'Tissue Paraffin Blocks', '5 Days', 'PATHOLOGY', 'PATHOLOGY', false, 'active');

-- Insert Packages
INSERT INTO packages (name, description, price, mrp, test_count, category, includes, status) VALUES
('New 69', 'Comprehensive health screening package with essential tests', 899, 899, 9, 'Health Checkup', 'Fasting Blood Sugar, Lipid Profile, Liver Function Profile, IRON PROFILE, Complete Urine Analysis (CUE), Glycosylated Hemoglobin (GHb/HBA1c), Calcium & Phosphorus, Thyroid Profile-II, Complete Blood Count + ESR, Kidney Basic screen', 'active'),
('New 79', 'Extended health package with vitamin and mineral screening', 1199, 1199, 12, 'Health Checkup', 'Fasting Blood Sugar, Lipid Profile, Liver Function Profile, IRON PROFILE, Complete Urine Analysis (CUE), Glycosylated Hemoglobin (GHb/HBA1c), Calcium & Phosphorus, Folate, Vitamin - B12 & 25-Hydroxy Vitamin D Total (D2 & D3), Thyroid Profile-II, Complete Blood Count + ESR, Kidney Basic screen', 'active'),
('New 89', 'Advanced health screening with cardiac and metabolic markers', 2199, 2199, 20, 'Health Checkup', 'Fasting Blood Sugar, Lipid Profile, Liver Function Profile, IRON PROFILE, Thyroid Profile-II, Complete Urine Analysis (CUE), Glycosylated Hemoglobin (GHb/HBA1c), Creatinine - 24 Hr Urine, Urine Albumin(Microalbumin)/Creatinine Ratio, Vitamin - B12 & 25-Hydroxy Vitamin D Total (D2 & D3), Calcium, Phosphorus, Amylase, Lipase, LDH, hsCRP, Ferritin, Complete Blood Count + ESR, Homocysteine, Kidney Basic screen', 'active'),
('New 99 Male', 'Comprehensive male health package with prostate screening', 2999, 2999, 27, 'Health Checkup', 'Lipid Profile, Liver Function Profile, IRON PROFILE, Prostate Specific Antigen (PSA) Total, Complete Urine Analysis (CUE), Urine Albumin(Microalbumin)/Creatinine Ratio, Glucose - Fasting, Fasting Urine Glucose, Glucose - Postprandial, Post Prandial Urine Glucose, Glycosylated Hemoglobin (GHb/HBA1c), Homocysteine, Vitamin - B12 & 25-Hydroxy Vitamin D Total (D2 & D3), Calcium, Phosphorus, Amylase, Lipase, LDH, hsCRP, Ferritin, Zinc, CK, Testosterone, APO-A1, APO-B, Thyroid Profile-I, Complete Blood Count (CBC), Kidney Basic screen', 'active'),
('New 99 Female', 'Comprehensive female health package with cancer marker screening', 2999, 2999, 27, 'Health Checkup', 'Lipid Profile, Liver Function Profile, IRON PROFILE, CA 125 Ovarian Cancer marker, Complete Urine Analysis (CUE), Urine Albumin(Microalbumin)/Creatinine Ratio, Glucose - Fasting, Fasting Urine Glucose, Glucose - Postprandial, Post Prandial Urine Glucose, Glycosylated Hemoglobin (GHb/HBA1c), Homocysteine, Vitamin - B12 & 25-Hydroxy Vitamin D Total (D2 & D3), Calcium, Phosphorus, Amylase, Lipase, LDH, hsCRP, Ferritin, Zinc, CK, Testosterone, APO-A1, APO-B, Thyroid Profile-I, Complete Blood Count (CBC), Kidney Basic screen', 'active'),
('Anaemia Basic Screen', 'Complete anemia screening with iron studies', 1000, 1000, 7, 'Specialized', 'Iron, Ferritin, Iron Binding Capacity - Total (TIBC), Transferrin, Vitamin - B12, Transferrin %, Complete Blood Count (CBC)', 'active'),
('Thyroid Screening', 'Comprehensive thyroid function and antibody screening', 1999, 1999, 9, 'Specialized', 'Anti Microsomal/Thryroperoxidase Antibody (Anti TPO), Anti Thyroglobulin Antibody (ATG), Calcitonin Serum, Thyroglobulin, Triiodothyronine Total (TT3), Thyroxine - Total (TT4), Triiodothyronine Free (FT3), Thyroxine - Free (FT4), Thyroid Stimulating Hormone (TSH)', 'active'),
('Fever Basic Screen', 'Essential fever investigation package', 899, 899, 5, 'Specialized', 'Erythrocyte Sedimentation Rate (ESR), Malarial Parasite Identification, Widal Test (Slide Test), C-Reactive Protein (CRP), Complete Blood Count (CBC)', 'active');
